# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1a76cd7bfb0a974ca4ce93e94653d18cc766df28b474630cd9be7bb2c7f55d2d2399af4ab76b94544ffe9d6be33189f8f011ae3171a193b2e52cdfe1975a8d4

test:
  secret_key_base: f423952c581975614e83f50196f7027f2e774b8366cf8b925890f59246fcc3afddaa4d3d94ff8efaec3415f682a1b3285b36a8c430ac0a091478c362dddfbfc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
